name: wechat
description: "仿微信UI实战."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  equatable:

  wc_account:
    path: packages/wc_account
  wc_services:
    path: packages/wc_services
  wc_tool:
    path: packages/wc_tool

  cupertino_icons:
  go_router:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
flutter:
  uses-material-design: true
